import("std.lua")

local function scene1()
    scene_set_background(load_image("bg.png"))
    scene_add_animation(load_image("trixie1.png"), 4, 4, 10, 100, 0, 1, {2, 3, 5, 6, 4, 1})
    dialog("HEY, HEY!!! ARE YOU ASLEEP?\nC'MON! ANSWER THE GREAT TRIXIE!")
    scene_clear()
    scene_add_animation(load_image("trixie2.png"), 7, 7, 7, 100, 0, 1, {2, 3, 4, 5, 6, 7, 11, [11]=13, [13]=12, [12]=18, [18]=5})
    dialog("THAT'S BETTER. TRIXIE SHALL\nSTART EXPLAINING THE RULES.")
    scene_clear()
    scene_add_animation(load_image("trixie3.png"), 4, 4, 7, 100, 0, 1, {2, 3, 4, 5, 7, 1, 6})
    scene_add_animation(load_image("trixie-magic.png"), 13, 13, 10, 210, -40, 1, {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 11})
    dialog("THE SPELL THAT TURNS YOU INTO\nA PONY LASTS THREE DAYS.")
    dialog("AFTER THAT, YOU'LL TURN BACK\nTO HUMAN. HAVE A GOOD TIME.")
    scene_clear()
    scene_set_background(load_image("ground.png"))
    scene_add_image(load_image("hooves.png"), 100, 0)
    scene_add_animation(load_image("hooves-magic.png"), 9, 9, 14, 0, 0, 1, {2, 3, 4, 5, 6, 7, 8, 9, nil})
    scene_play()
    scene_clear()
    scene_set_background(load_image("bg2.png"))
    scene_add_animation(load_image("rumpa.png"), 9, 9, 14, 0, 0, 1, {2, 3, 4, 5, 6, 7, 8, 9, nil})
    scene_play()
    scene_clear()
    scene_set_background(load_image("ground.png"))
    scene_add_image(load_image("hooves2.png"), 100, 0)
    scene_add_animation(load_image("tail.png"), 5, 5, 14, 0, 0, 1, {2, 3, 4, 5, nil})
    scene_play()
    sleep(10000)
end

scene1()